import avatar from "./assets/avatar.jpg";
import avatar2 from "./assets/avatar2.jpg";
import avatar3 from "./assets/avatar3.jpg";
import avatar4 from "./assets/avatar4.jpg";
import avatar5 from "./assets/avatar5.jpg";
import avatar6 from "./assets/avatar6.jpg";
import avatar7 from "./assets/avatar7.jpg";
import avatar8 from "./assets/myself.jpeg";
import product1 from "./assets/product1.jpg";
import product2 from "./assets/product2.jpg";
import product3 from "./assets/product3.jpg";
import product4 from "./assets/product4.jpg";
import product5 from "./assets/product5.jpg";
import product6 from "./assets/product6.jpg";
import product7 from "./assets/product7.jpg";
import product8 from "./assets/product8.jpg";


// employee data
export const employeesData = [
  {
    EmployeeID: 1,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "Zambia",
    ReportsTo: "Bilal",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 2,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/04/2021",
    Country: "Tanzania",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 3,
    Name: "Abdi abdul",
    Title: "HR",
    HireDate: "01/06/2021",
    Country: "Kenya",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 4,
    Name: "Hafsa Nuh",
    Title: "Marketing Head",
    HireDate: "01/01/2020",
    Country: "Malaysia",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 5,
    Name: "Yahya Omar",
    Title: "HR",
    HireDate: "01/02/2020",
    Country: "Canada",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar5,
  },
  {
    EmployeeID: 6,
    Name: "Iyan Penjani",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar6,
  },
  {
    EmployeeID: 7,
    Name: "Ahmed Vitold",
    Title: "HR",
    HireDate: "01/05/2020",
    Country: "South Africa",
    ReportsTo: "Randell",
    EmployeeImage: avatar7,
  },
  {
    EmployeeID: 8,
    Name: "Hali Davolio",
    Title: "Sales Representative",
    HireDate: "01/01/2019",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar8,
  },
  {
    EmployeeID: 9,
    Name: "Danai Nasimiyu",
    Title: "Marketing Head",
    HireDate: "01/01/2021",
    Country: "Botswana",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar6,
  },
  {
    EmployeeID: 10,
    Name: "Ali Albu",
    Title: "HR",
    HireDate: "01/07/2020",
    Country: "Malawi",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar5,
  },
  {
    EmployeeID: 11,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 12,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 13,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 14,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 15,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 16,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 17,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 18,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 19,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 20,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 21,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 22,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 23,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 24,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 25,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 26,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 27,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 28,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 29,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 30,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 31,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 32,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 33,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 34,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 35,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 36,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 37,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 38,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 39,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 40,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 41,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 42,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 43,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 44,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 45,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 46,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 47,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 48,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 49,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 50,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 51,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 52,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 53,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 54,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 55,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 56,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 57,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 58,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 59,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 60,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 61,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 62,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 63,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
  },
];

// assests data
export const ordersData = [
  {
    OrderID: 10248,
    CustomerName: "Vinet",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage: product6,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 345653,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    OrderItems: "Butter Scotch",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "Delhi",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product5,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 390457,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    OrderItems: "Candy Gucci",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "New York",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product7,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 893486,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    OrderItems: "Night Lamp",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "Germany",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product4,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 748975,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "Spain",
    Status: "rejected",
    StatusBg: "red",
    ProductImage: product1,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 94757,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "USA",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product2,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 944895,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    OrderItems: "Skincare",
    Location: "USA",
    Status: "active",
    StatusBg: "#03C9D7",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    ProductImage: product3,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 845954,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product4,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 845954,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "USA",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 38489,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 24546,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "USA",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
  },
  {
    OrderID: 10248,
    CustomerName: "Vinet",
    ReleasedYear: "01/02/2021",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    Status: "pending",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FB9678",
    ProductImage: product6,
  },
  {
    OrderID: 345653,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    OrderItems: "Butter Scotch",
    Location: "Delhi",
    Status: "complete",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#8BE78B",
    ProductImage: product5,
  },
  {
    OrderID: 390457,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    OrderItems: "Candy Gucci",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "New York",
    Status: "active",
    link: "edit",
    link1: "delete",
    StatusBg: "#03C9D7",
    ProductImage: product7,
  },
  {
    OrderID: 893486,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    OrderItems: "Night Lamp",
    Location: "Germany",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    link: "edit",
    link1: "delete",
    ProductImage: product4,
  },
  {
    OrderID: 748975,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Location: "Spain",
    Status: "rejected",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "red",
    link: "edit",
    link1: "delete",
    ProductImage: product1,
  },
  {
    OrderID: 94757,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Location: "USA",
    Status: "canceled",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FF5C8E",
    link: "edit",
    link1: "delete",
    ProductImage: product2,
  },
  {
    OrderID: 944895,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    OrderItems: "Skincare",
    Location: "USA",
    Status: "active",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#03C9D7",
    link: "edit",
    link1: "delete",
    ProductImage: product3,
  },
  {
    OrderID: 845954,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Status: "complete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#8BE78B",
    link: "edit",
    link1: "delete",
    ProductImage: product4,
  },
  {
    OrderID: 845954,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
  },
  {
    OrderID: 38489,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
  },
  {
    OrderID: 24546,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
  },
  {
    OrderID: 10248,
    CustomerName: "Vinet",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    ReleasedYear: "01/02/2021",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    link: "edit",
    link1: "delete",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage: product6,
  },
  {
    OrderID: 345653,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    OrderItems: "Butter Scotch",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "Delhi",
    Status: "complete",
    StatusBg: "#8BE78B",
    link: "edit",
    link1: "delete",
    ProductImage: product5,
  },
  {
    OrderID: 390457,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    OrderItems: "Candy Gucci",
    Location: "New York",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    link: "edit",
    link1: "delete",
    ProductImage: product7,
  },
  {
    OrderID: 893486,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    OrderItems: "Night Lamp",
    Location: "Germany",
    Status: "canceled",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FF5C8E",
    link: "edit",
    link1: "delete",
    ProductImage: product4,
  },
  {
    OrderID: 748975,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Location: "Spain",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "rejected",
    StatusBg: "red",
    ProductImage: product1,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 94757,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product2,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 944895,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Skincare",
    Location: "USA",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product3,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 845954,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product4,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 845954,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
  },
  {
    OrderID: 38489,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
  },
  {
    OrderID: 24546,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "USA",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
  },
  {
    OrderID: 10248,
    CustomerName: "Vinet",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    ReleasedYear: "01/02/2021",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    link: "edit",
    link1: "delete",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage: product6,
  },
  {
    OrderID: 345653,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Butter Scotch",
    Location: "Delhi",
    Status: "complete",
    link: "edit",
    link1: "delete",
    StatusBg: "#8BE78B",
    ProductImage: product5,
  },
  {
    OrderID: 390457,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Candy Gucci",
    Location: "New York",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product7,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 893486,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Night Lamp",
    Location: "Germany",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product4,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 748975,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Location: "Spain",
    Status: "rejected",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "red",
    ProductImage: product1,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 94757,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Location: "USA",
    Status: "canceled",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FF5C8E",
    ProductImage: product2,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 944895,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    OrderItems: "Skincare",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product3,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 845954,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product4,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 845954,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
  },
  {
    OrderID: 38489,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
  },
  {
    OrderID: 24546,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    Status: "complete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#8BE78B",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
  },
  {
    OrderID: 10248,
    CustomerName: "Vinet",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    ReleasedYear: "01/02/2021",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    link: "edit",
    link1: "delete",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage: product6,
  },
  {
    OrderID: 345653,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    OrderItems: "Butter Scotch",
    Location: "Delhi",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product5,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 390457,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    OrderItems: "Candy Gucci",
    Location: "New York",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product7,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 893486,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    OrderItems: "Night Lamp",
    Location: "Germany",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product4,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 748975,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Location: "Spain",
    Status: "rejected",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "red",
    ProductImage: product1,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 94757,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Location: "USA",
    Status: "canceled",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FF5C8E",
    ProductImage: product2,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 944895,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    OrderItems: "Skincare",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product3,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 845954,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product4,
    link: "edit",
    link1: "delete",
  },
  {
    OrderID: 845954,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    link: "edit",
    link1: "delete",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    link: "edit",
    link1: "delete",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
  },
  {
    OrderID: 38489,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    link: "edit",
    link1: "delete",
    StatusBg: "#03C9D7",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
  },
  {
    OrderID: 24546,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    link: "edit",
    link1: "delete",
    StatusBg: "#8BE78B",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
  },
  {
    OrderID: 874534,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    link: "edit",
    link1: "delete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
  },
];
