import avatar from "./assets/avatar.jpg";
import avatar2 from "./assets/avatar2.jpg";
import avatar3 from "./assets/avatar3.jpg";
import avatar4 from "./assets/avatar4.jpg";
import avatar5 from "./assets/avatar5.jpg";
import avatar6 from "./assets/avatar6.jpg";
import avatar7 from "./assets/avatar7.jpg";
import avatar8 from "./assets/myself.jpeg";

// employee data
export const employeesData = [
  {
    EmployeeID: 1,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "Zambia",
    ReportsTo: "Bilal",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 2,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/04/2021",
    Country: "Tanzania",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 3,
    Name: "Abdi abdul",
    Title: "HR",
    HireDate: "01/06/2021",
    Country: "Kenya",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 4,
    Name: "Hafsa Nuh",
    Title: "Marketing Head",
    HireDate: "01/01/2020",
    Country: "Malaysia",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 5,
    Name: "Yahya Omar",
    Title: "HR",
    HireDate: "01/02/2020",
    Country: "Canada",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar5,
  },
  {
    EmployeeID: 6,
    Name: "Iyan Penjani",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar6,
  },
  {
    EmployeeID: 7,
    Name: "Ahmed Vitold",
    Title: "HR",
    HireDate: "01/05/2020",
    Country: "South Africa",
    ReportsTo: "Randell",
    EmployeeImage: avatar7,
  },
  {
    EmployeeID: 8,
    Name: "Hali Davolio",
    Title: "Sales Representative",
    HireDate: "01/01/2019",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar8,
  },
  {
    EmployeeID: 9,
    Name: "Danai Nasimiyu",
    Title: "Marketing Head",
    HireDate: "01/01/2021",
    Country: "Botswana",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar6,
  },
  {
    EmployeeID: 10,
    Name: "Ali Albu",
    Title: "HR",
    HireDate: "01/07/2020",
    Country: "Malawi",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar5,
  },
  {
    EmployeeID: 11,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 12,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 13,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 14,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 15,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 16,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 17,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 18,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 19,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 20,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 21,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 22,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 23,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 24,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 25,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 26,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 27,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 28,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 29,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 30,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 31,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 32,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 33,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 34,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 35,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 36,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 37,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 38,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 39,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 40,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 41,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 42,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 43,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 44,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 45,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 46,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 47,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 48,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 49,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 50,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 51,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 52,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 53,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 54,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 55,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 56,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 57,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 58,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar3,
  },
  {
    EmployeeID: 59,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar4,
  },
  {
    EmployeeID: 60,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
  },
  {
    EmployeeID: 61,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 62,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
  },
  {
    EmployeeID: 63,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
  },
];
