import avatar from "./assets/avatar.jpg";
import avatar2 from "./assets/avatar2.jpg";
import avatar3 from "./assets/avatar3.jpg";
import avatar4 from "./assets/avatar4.jpg";
import avatar5 from "./assets/avatar5.jpg";
import avatar6 from "./assets/avatar6.jpg";
import avatar7 from "./assets/avatar7.jpg";
import avatar8 from "./assets/myself.jpeg";
import product1 from "./assets/product1.jpg";
import product2 from "./assets/product2.jpg";
import product3 from "./assets/product3.jpg";
import product4 from "./assets/product4.jpg";
import product5 from "./assets/product5.jpg";
import product6 from "./assets/product6.jpg";
import product7 from "./assets/product7.jpg";
import product8 from "./assets/product8.jpg";

// 
import {BsCurrencyDollar,BsShield,} from "react-icons/bs";
import { AiFillEdit, AiFillDelete, AiFillEye } from "react-icons/ai";


// employee data
export const employeesData = [
  {
    EmployeeID: 1,
    Name: "Davolio Nancy",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "Zambia",
    ReportsTo: "Bilal",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 2,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/04/2021",
    Country: "Tanzania",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 3,
    Name: "Abdi abdul",
    Title: "HR",
    HireDate: "01/06/2021",
    Country: "Kenya",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar3,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 4,
    Name: "Hafsa Nuh",
    Title: "Marketing Head",
    HireDate: "01/01/2020",
    Country: "Malaysia",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 5,
    Name: "Yahya Omar",
    Title: "HR",
    HireDate: "01/02/2020",
    Country: "Canada",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar5,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 6,
    Name: "Iyan Penjani",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar6,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 7,
    Name: "Ahmed Vitold",
    Title: "HR",
    HireDate: "01/05/2020",
    Country: "South Africa",
    ReportsTo: "Randell",
    EmployeeImage: avatar7,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 8,
    Name: "Hali Davolio",
    Title: "Sales Representative",
    HireDate: "01/01/2019",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar8,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 9,
    Name: "Danai Nasimiyu",
    Title: "Marketing Head",
    HireDate: "01/01/2021",
    Country: "Botswana",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar6,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 10,
    Name: "Ali Albu",
    Title: "HR",
    HireDate: "01/07/2020",
    Country: "Malawi",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar5,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 11,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 12,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 13,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 14,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 15,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 16,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar3,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 17,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar4,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 18,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 19,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 20,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar3,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 21,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 22,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 23,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar3,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 24,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 25,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 26,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 27,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 28,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 29,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 30,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar3,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 31,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 32,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 33,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 34,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 35,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 36,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 37,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar3,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 38,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 39,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 40,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 41,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 42,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 43,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 44,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar3,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 45,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar4,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 46,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 47,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 48,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 49,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 50,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 51,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar3,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 52,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar4,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 53,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 54,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 55,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Patrobas",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 56,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 57,
    Name: "Nancy Davolio",
    Title: "Sales Representative",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 58,
    Name: "Nasimiyu Danai",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar3,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 59,
    Name: "Iulia Albu",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Randell",
    EmployeeImage: avatar4,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 60,
    Name: "Siegbert Gottfried",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 61,
    Name: "Omar Darobe",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Hafsa",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 62,
    Name: "Penjani Inyene",
    Title: "Marketing Head",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Geoffrey",
    EmployeeImage: avatar,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
  {
    EmployeeID: 63,
    Name: "Miron Vitold",
    Title: "HR",
    HireDate: "01/02/2021",
    Country: "USA",
    ReportsTo: "Bilal",
    EmployeeImage: avatar2,
    link: <AiFillEdit />,
    link1: <AiFillDelete />,
  },
];

// assests data
export const ordersData = [
  {
    OrderID: 1,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    OrderItems: "Night Lamp",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "Germany",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 2,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "USA",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product2,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 3,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    OrderItems: "Skincare",
    Location: "USA",
    Status: "active",
    StatusBg: "#03C9D7",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    ProductImage: product3,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 4,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 5,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 6,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "USA",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 7,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 8,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 9,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "USA",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 10,
    CustomerName: "Vinet",
    ReleasedYear: "01/02/2021",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    Status: "pending",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FB9678",
    ProductImage: product6,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 11,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    OrderItems: "Butter Scotch",
    Location: "Delhi",
    Status: "complete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#8BE78B",
    ProductImage: product5,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 12,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    OrderItems: "Candy Gucci",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "New York",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product7,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 13,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    OrderItems: "Night Lamp",
    Location: "Germany",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 14,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Location: "Spain",
    Status: "rejected",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "red",
    ProductImage: product1,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 15,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Location: "USA",
    Status: "canceled",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FF5C8E",
    ProductImage: product2,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 16,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    OrderItems: "Skincare",
    Location: "USA",
    Status: "active",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#03C9D7",
    ProductImage: product3,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 17,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Status: "complete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#8BE78B",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 18,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 19,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 20,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 21,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 22,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 23,
    CustomerName: "Vinet",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    ReleasedYear: "01/02/2021",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage: product6,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 24,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    OrderItems: "Butter Scotch",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "Delhi",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product5,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 25,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    OrderItems: "Candy Gucci",
    Location: "New York",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product7,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 26,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    OrderItems: "Night Lamp",
    Location: "Germany",
    Status: "canceled",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FF5C8E",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 27,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Location: "Spain",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "rejected",
    StatusBg: "red",
    ProductImage: product1,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 28,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product2,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 29,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Skincare",
    Location: "USA",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product3,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 30,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 31,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 32,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 33,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 34,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 35,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "USA",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 36,
    CustomerName: "Vinet",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    ReleasedYear: "01/02/2021",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage: product6,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 37,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Butter Scotch",
    Location: "Delhi",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product5,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 38,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Candy Gucci",
    Location: "New York",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product7,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 39,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Night Lamp",
    Location: "Germany",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 40,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Location: "Spain",
    Status: "rejected",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "red",
    ProductImage: product1,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 41,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Location: "USA",
    Status: "canceled",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FF5C8E",
    ProductImage: product2,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 42,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    OrderItems: "Skincare",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product3,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 43,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 44,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 45,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 46,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 47,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    Status: "complete",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#8BE78B",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 48,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 49,
    CustomerName: "Vinet",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    ReleasedYear: "01/02/2021",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage: product6,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 50,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    OrderItems: "Butter Scotch",
    Location: "Delhi",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product5,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 51,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    OrderItems: "Candy Gucci",
    Location: "New York",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product7,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 52,
    CustomerName: "Anika Viseer",
    ReleasedYear: "01/02/2021",
    OrderItems: "Night Lamp",
    Location: "Germany",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 53,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Location: "Spain",
    Status: "rejected",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "red",
    ProductImage: product1,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 54,
    CustomerName: "Omar Darobe",
    ReleasedYear: "01/02/2021",
    OrderItems: "Makeup Lancome Rouge",
    Location: "USA",
    Status: "canceled",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    StatusBg: "#FF5C8E",
    ProductImage: product2,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 55,
    CustomerName: "Lulia albu",
    ReleasedYear: "01/02/2021",
    OrderItems: "Skincare",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product3,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 56,
    CustomerName: "Penjani",
    ReleasedYear: "01/02/2021",
    OrderItems: "Headphone",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product4,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 57,
    CustomerName: "Jie Yan",
    ReleasedYear: "01/02/2021",
    OrderItems: "Shoes",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage:
      "https://cdn.shopclues.com/images1/thumbnails/104158/320/320/148648730-104158193-1592481791.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 58,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 59,
    CustomerName: "Miron",
    ReleasedYear: "01/02/2021",
    OrderItems: "Ice Cream",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/dairy-free-ice-cream-eae372d.jpg",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 60,
    CustomerName: "Frank",
    ReleasedYear: "01/02/2021",
    OrderItems: "Pan Cake",
    Location: "Delhi",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage:
      "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1480&q=80",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 61,
    CustomerName: "Danai",
    ReleasedYear: "01/02/2021",
    OrderItems: "Watch",
    Location: "USA",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Status: "canceled",
    StatusBg: "#FF5C8E",
    ProductImage:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/pop-womens-garmin-watches-1641919013.jpg?crop=0.502xw:1.00xh;0.250xw,0&resize=640:*",
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 62,
    CustomerName: "Vinet",
    ReleasedYear: "01/02/2021",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    OrderItems: "Fresh Tomato",
    Location: "USA",
    Status: "pending",
    StatusBg: "#FB9678",
    ProductImage: product6,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 63,
    CustomerName: "Carson Darrin",
    ReleasedYear: "01/02/2021",
    OrderItems: "Butter Scotch",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "Delhi",
    Status: "complete",
    StatusBg: "#8BE78B",
    ProductImage: product5,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 64,
    CustomerName: "Fran Perez",
    ReleasedYear: "01/02/2021",
    OrderItems: "Candy Gucci",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "New York",
    Status: "active",
    StatusBg: "#03C9D7",
    ProductImage: product7,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
  {
    OrderID: 65,
    CustomerName: "Miron Vitold",
    ReleasedYear: "01/02/2021",
    OrderItems: "Healthcare Erbology",
    Description:
      "Equity is the debt-free evaluation of held assets or the difference between assets and liabilities",
    Location: "Spain",
    Status: "rejected",
    StatusBg: "red",
    ProductImage: product1,
    link: <AiFillEye />,
    link1: <AiFillEdit />,
    link2: <AiFillDelete />,
  },
];

// user data
export const userProfileData = [
  {
    icon: <BsCurrencyDollar />,
    title: "My Profile",
    desc: "Account Settings",
    iconColor: "#03C9D7",
    iconBg: "#E5FAFB",
  },
  {
    icon: <BsShield />,
    title: "My Inbox",
    desc: "Messages & Emails",
    iconColor: "rgb(0, 194, 146)",
    iconBg: "rgb(235, 250, 242)",
  },
];

// FAQ data
export const TriviaQuestion = [
  {
    headingID: 1,
    question: "An Important Question?",
    answer:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendissemalesuada lacus ex, sit amet blandit leo lobortis ege",
  },
  {
    headingID: 2,
    question: "Another Important Question?",
    answer:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendissemalesuada lacus ex, sit amet blandit leo lobortis ege",
  },
  {
    headingID: 3,
    question: "Your Favorite Question?",
    answer:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendissemalesuada lacus ex, sit amet blandit leo lobortis ege",
  },
  {
    headingID: 4,
    question: "Some Random Question?",
    answer:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendissemalesuada lacus ex, sit amet blandit leo lobortis ege",
  },
  {
    headingID: 5,
    question: "The Final Question?",
    answer:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendissemalesuada lacus ex, sit amet blandit leo lobortis ege",
  },
];
